site_name: Unofficial iRODS Documentation
theme:
  name: readthedocs
  favicon: docs/img/favicon.ico
nav:
    - Home: index.md
    - About: About.md
    - Developer:
      - "Brief overview": Developer.md
      - "Python API": PythonAPI.md
    - Database:
      - "Tuning": Database_tuning.md
    - System Administration:
      - "Usefull Queries": Queries.md
      - "Setup": Server_setup.md

    # - "Initial deployment"
    # - "Metrics and monitoring"
    # - "Zone Management"
    # - "Misc best practices"
    # - Resources
    #   - "Compound Trees"
    #   - "File system resources"
    #   - "S3 resources"
