name: "mkdocs: check"

on:
  - push
  - pull_request

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.10.13'
          architecture: 'x64'

      - name: Install dependencies
        run: |
          python3 -m pip install pipenv
          pipenv --python 3
          pipenv install
      - run: cd unofficial_irods_documentation && pipenv run mkdocs build
